### PR TITLE
Updated stack detection to occur later

### PR DESCRIPTION
**Pull request by faceleg**
It seems express 4 does not add _router immediately, checking for it on connectr init was causing the whole thing to collapse in flames.

Threw in some other minor updates.

### CODE REVIEW

**Comment by olalonde** [comment]
Hey @faceleg , sorry I was off GH recently. I added you as a collaborator :+1: Just let me know when I should push to  npm.

**Comment by faceleg** [comment]
Hi @olalonde, thanks! I've merged - you should be OK to bump the version and push to NPM at will.

If you've not got the time, feel free to make me an owner on NPM?

https://docs.npmjs.com/cli/owner

**Comment by olalonde** [comment]
@faceleg added you as a owner on the npm package :+1: You can bump the version.

**Comment by faceleg** [comment]
Done, thanks :)

**Pull request merged**
